### ISSUE TITLE
converter require path missing one more folder step out/up

### ISSUE THREAD

**Issue by sushidub** [mrodrig/json-2-csv-cli#1]
More of an fyi than an issue (for me anyways).
From the context of having installed both `json-2-csv` and `@mrodrig/json-2-csv-cli` with the global flag `npm install -g`

Within: `utils.js`
this doesn't work: `converter = require('../../../json-2-csv');`
this works: `converter = require('../../../../json-2-csv');`

**Comment by mrodrig** [comment]
Thanks for reporting this @sushidub! Good find! I thought I had switched everything over when I pulled the CLI functionality out to its own module, but must've missed that spot. I'll update it so the path is correct. Thanks again!
